name: tiutiu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  mask_text_input_formatter: ^2.3.0
  firebase_dynamic_links: ^5.0.4
  flutter_facebook_auth: ^5.0.1
  font_awesome_flutter: ^10.1.0
  flutter_screenutil: ^5.5.3+2
  cached_network_image: ^3.2.1  
  firebase_messaging: ^14.0.4
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  firebase_analytics: ^10.0.4
  sign_in_with_apple: ^4.1.0
  loading_animations: ^2.2.0
  flutter_speed_dial: ^6.0.0  
  firebase_database: ^10.0.4
  firebase_storage: ^11.0.4
  connectivity_plus: ^2.3.7
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^4.0.4
  cupertino_icons: ^1.0.5
  auto_size_text: ^3.0.0
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3  
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  maps_launcher: ^2.0.1  
  brasil_fields: ^1.6.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5
  share_plus: ^4.0.10
  geolocator: ^9.0.1
  geocoding: ^2.0.5  
  provider: ^6.0.3
  sqflite: ^2.0.3
  intl: ^0.17.0  
  uuid: ^3.0.6
  video_player:
  dio: ^4.0.6
  get: ^4.6.5
  chewie:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  pedantic: any

flutter:

  uses-material-design: true  
  assets:    
    - assets/startscreen/
    - assets/json/
    - assets/webp/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:           
    - family:  Tiutiu
      fonts:
       - asset: fonts/Tiutiu.ttf
    - family:  Gender
      fonts:
       - asset: fonts/Gender.ttf
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Bold.ttf
        - asset: fonts/Rajdhani-Light.ttf
        - asset: fonts/Rajdhani-Medium.ttf
        - asset: fonts/Rajdhani-Regular.ttf
        - asset: fonts/Rajdhani-SemiBold.ttf          
          weight: 700    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages